### ISSUE TITLE
No Events Message

### ISSUE THREAD

**Issue by AntoineT7** [MilanKacurak/FormatGoogleCalendar#10]
This has been a crucial help, so first and foremost, thank you! I'm new to js and I'm trying to figure out where could incorporate a "No Events to Show" message when the list is empty, if that's possible.

**Comment by AntoineT7** [comment]
Never mind, I figured it out! Added two more if statements:
`if ($upcomingElem.children().length == 0) {` 
`if ($pastElem.children().length == 0) {`
and appended the message there.

**Comment by MilanLund** [comment]
@AntoineT7  Sorry for not supporting this on a regular basis. I see you have done some more updates to the code on your own which I appreciate.

To give you more background... I created this code for one of my clients according to his needs and shared it with the community. As the client is happy with the library and I have plenty of other work I support this repository very rarely and not planning adding any more features. 

If you make any enhancement the community would appreciate if you share it by a pull request. Thank you.
