### ISSUE TITLE
recurring events & Min Time

### ISSUE THREAD

**Issue by rwokano** [MilanKacurak/FormatGoogleCalendar#11]
Hi !
    This is a great piece of code, Thanks for sharing.  A couple of suggestions for future enhancements below.
1. The calendar I am accessing is for a group that meets weekly, and they set up the calendar years ago with a recurring event.  I need to be able to add the singleEvents=true in order for the calendar to return a unique event for each meeting date.  I was able to do this by putting it in the calendar URL.   
2. Along the same lines, it seems that the call is returning a max of 250 (249) items?  Given my above problem, there are way more than 250.  So my list will not show any future items because they are never read in.  I added the timeMin param into the URL as above, and that fixed it. 
   
   It might be nice to have these two as a parameter rather than adding to the calendar URL. It is up to you just a suggestion.
   
   Thanks again for sharing this code!

**Comment by AlexVilla** [comment]
Hi @rwokano i had the same problem with the number of events returned, the problem in this seccion is google, you have to add `&maxResults=NumberOfResults` to the URL to set the maximum number of results you want, for example  `&maxResults=2500` will give you 2500 events, maybe for make this more simple the numer of results can be an option in the init function and make that the script join the number to the url, but if you can do manually no problem ;)

**Comment by MilanLund** [comment]
@AlexVilla Thanks for the reply! @rwokano You are able to add url parameters directly in your calendar url. 
In terms of the `singleEvents=true` parameter I experienced some issues on the Google side. Basically, having this parameter in the url Google doesn't return some events in the JSON even if they should have been there.
