### ISSUE TITLE
I'm perplexed! It's not working for me all the time.

### ISSUE THREAD

**Issue by Chiggers** [MilanKacurak/FormatGoogleCalendar#13]
Hello!

Long story short I'm using this script across 30 or so websites and it works great, but only on about 75% of the websites (each website has its own calendar). I cannot for the life of me figure out why the remaining 25% do not work. It has something to do with the calendar itself. Here's my error checking

- I've copied and pasted code, ensuring I only change what must be changed (calendarID).
- I've verified that the GET request is going through, and that JSON is returned populated with events... but those don't show on the website.
- The calendar is publicly shared and accessible and is already on the website on a "calendar" page, I just cannot get the events to show on the homepage as a list on some of the 30 websites.
- On websites where the event list IS working, I've copied and pasted that calendarID onto a website where it is not working, and it works fine, telling me that the issue is with the calendar itself, not with the website.
- On websites where the event list is working, I've copied and pasted a calendarID that doesn't work, and of course it doesn't work.
- I've taken the code to a 3rd party non-related website and stripped the code down to just the calendar, and again, the calendarIDs that worked before still work, and the calendarIDs that didn't work before do not work.

Any ideas why one calendarID might work and another calendarID might not?

Thanks for the help!

**Comment by PTST** [comment]
Have you remembered to set the calendar to public?

**Comment by MilanLund** [comment]
Well, I would try to request the calendar url directly in the browser. Google will return a message in case of any issue. If you will be given a long JSON with all the events I would take a look in the browser console for js errors.

**Comment by Chiggers** [comment]
Thanks for the help!

I kinda gave up on this issue. I have no explanation. Yes the calendar is public. It is already viewable on another page on the same website and working correctly.

I loaded the calendar URL into the browser and the JSON looks great. All items in the calendar are there and viewable. Viewing this and the website in FirefoxDeveloperEdition and there are no JS errors or anything. It works perfectly fine with one calendarID and not with another.
