### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by agyrafa** [MilanKacurak/FormatGoogleCalendar#14]
Im getting this error
`{ `
`    "error": {`
 ` "errors": [`
  ` {`
   ` "domain": "global",`
   ` "reason": "notFound",`
 `   "message": "Not Found"`
`   }`
  `],`
  `"code": 404,`
 ` "message": "Not Found"`
 `}`
`}`

anyone can help?

**Comment by Chiggers** [comment]
Doublecheck you have your calendar ID right in the calendar URL, and make sure your calendar is set to public. If your URL is right and your calendar is shared then you should be able to put that URL in a browser and see the information that is returned.

**Comment by agyrafa** [comment]
I got it... The calendar was private.
