### ISSUE TITLE
Possible to not add date to same same day events?

### ISSUE THREAD

**Issue by PTST** [MilanKacurak/FormatGoogleCalendar#18]
If i have to events on the same date, i only want to display the time, and not the date again. Is that possible?

**Comment by MilanLund** [comment]
It is not possible at this stage. To add this feature we would need to re-consider structure of the "format" setting. Specifically, the *date* wildcard would have to be split into the date and time parts and then add more complexity into the rendering logic. Of course, we would need to think of the backward compatibility.
