### ISSUE TITLE
No upcoming events, and past events start at 2012

### ISSUE THREAD

**Issue by mwclarkson** [MilanKacurak/FormatGoogleCalendar#20]
This looks great, and was very easy to implement. Thank you for sharing.

Oddly, the Past Events seem to start at the very end of 2012 and Upcoming Events don't show at all.

I'm sure I'm being an idiot, but if you could spare 30s to steer me right it would be much appreciated.

**Comment by mwclarkson** [comment]
I'm a doofus - it's Google API's limit of 250 items returned (clearly in chronological order).

Is it possible to pull them in in reverse?

**Comment by MilanLund** [comment]
Hmm, do you think you can achieve that by adding &orderBy=StartTime to the calendarUrl? Check [https://developers.google.com/google-apps/calendar/v3/reference/events/list](https://developers.google.com/google-apps/calendar/v3/reference/events/list) for more info.

**Comment by MilanLund** [comment]
@mwclarkson  I am also thinking if you could limit the size of the response by the timeMax and timeMin url parameters.
