### ISSUE TITLE
Recurring Events showing all at once despite dates

### ISSUE THREAD

**Issue by JamesMcFall** [MilanKacurak/FormatGoogleCalendar#21]
Hi Milan.
Thanks for the plugin.

I'm having a little bit of trouble with it at the moment. 

**Recurring Events Disabled**
If I have recurringEvents set to false, the upcoming events show chronologically except any recurring events that we're past the initial event of, don't get shown.

![screen shot 2017-06-24 at 9 50 36 am](https://user-images.githubusercontent.com/1585517/27501628-9d0f9ac8-58c2-11e7-8c87-6babe81d421a.png)

**Recurring Events Enabled**
If I have recurringEvents enabled, it returns 6 events that are all out of whack (dates not ordered) that are the recurring events of an event that was started in the past. Note none of the other events from today on are showing because these recurring ones are taking up the slots.

![screen shot 2017-06-24 at 9 48 03 am](https://user-images.githubusercontent.com/1585517/27501556-3f71b7f2-58c2-11e7-95ac-4d81708e4670.png)

* * *

So it seems like both versions of the flag may be slightly broken (definitely the recurringEvents: true; one).

Thanks

**Comment by MilanLund** [comment]
Hi @JamesMcFall,
In case of the recurringEvents option, someone else had a similar problem and made a pull request that solves it. Could you please get a new version of the library in the dist folder to check whether it does the work for you?
