### ISSUE TITLE
Working with events without time

### ISSUE THREAD

**Issue by dicksonguchu** [MilanKacurak/FormatGoogleCalendar#24]
Hi Milan,

I am having an issue when pulling events that don't have a set time. The dates of the events are appearing 1 day late. 
Please assist

**Comment by MilanLund** [comment]
Hi @richienj,
I experienced the issue as well. I have slightly re-implemented the library and it seems to be working for my tests now. Could you please get a new version in /dist/format-google-calendar.min.js and check whether it is working for you?

**Comment by dicksonguchu** [comment]
Thanks Milan..Will test it
