### ISSUE TITLE
FormatGoogleCalendar not working

### ISSUE THREAD

**Issue by huttee** [MilanKacurak/FormatGoogleCalendar#25]
I downloaded the files [https://www.milanlund.com/blog/javascript-library-google-calendar](here) and everything works. I substitute my calendar url and api and I get a blank screen. Put back Milan's calendar url and it works again.  I have tried various combinations of calendar url, client ID and api key. I even tried the service account.

Any ideas?

Thanks

**Comment by MilanLund** [comment]
Hi @huttee,
Could you please share your calendarUrl so I can check the situation by myself?

**Comment by huttee** [comment]
Hi,


Below is all the relevant information to my calendar. Using your code, my goal is to retrieve the events like this site (http://gotofirst.org) I came across.



Client ID
160090504394-s4m0rein6cn72fmbv5g3vmmgnnibtmu3.apps.googleusercontent.com
Client Secret
xKb7btSaKpnC4lWZ5udMX1Wz

Source:
src=qs8coo7qs58a2r3nhsvslj9398@group.calendar.google.com

https://calendar.google.com/calendar/embed?src=qs8coo7qs58a2r3nhsvslj9398@group.calendar.google.com&ctz=America/New_York
service account
ubccal@robust-root-179301.iam.gserviceaccount.com
client ID (service account)
103765809527942905988
Thanks for your help.

Huttee





-----Original Message-----

**Comment by MilanLund** [comment]
Hi @huttee,
Thanks a lot for the information. If you read my post here: https://www.milanlund.com/blog/javascript-library-google-calendar
there is a format for the calendarUrl you should follow: https://www.googleapis.com/calendar/v3/calendars/{calendarid}/events?key={Your Public API Key}

In your case:
- {calendarid} is qs8coo7qs58a2r3nhsvslj9398@group.calendar.google.com
- {Your Public API Key} is none of the information you've provided. You need to go to [https://console.developers.google.com](https://console.developers.google.com), create or select your project there, enable APIs in general, enable Calendar API and obtain your API key. You should be able to get it here:
![Image of Google Console](https://i.imgur.com/VUfR2Ej.png)

I have composed a demo for you: http://www.kacurak.com/formatgooglecalendar/huttee.html
The demo uses my API key. For your site use your own!
Please note that I added the &maxResults=2500 parameter to the caledarUrl to show as many events as possible. Read more about the url parameters for Google Calendar: https://developers.google.com/google-apps/calendar/v3/reference/events/list

**Comment by huttee** [comment]
Hey Milan,


Your screenshot below API Key did the trick. To get that screen I had to click on the dropdown arrow where it says "create credential". Always thought the client secret was same as api.  Once I was able to get the correct API, it works.


Thanks a lot for your help.


Huttee





-----Original Message-----
