### ISSUE TITLE
Websites in description

### ISSUE THREAD

**Issue by wmech16** [MilanKacurak/FormatGoogleCalendar#5]
I have a link in the description part. How do I make that link clickable? When it populates the link address is there but its not a hyperlink.

**Comment by MilanLund** [comment]
Regrettably, it is not supported at this stage. Moreover, Google does not allow you to insert links by default. Please, read more here: http://webapps.stackexchange.com/questions/27715/insert-hyperlink-in-google-calendars-description-field
