### ISSUE TITLE
[Feature Request] Private calendar

### ISSUE THREAD

**Issue by jonathanwinter123** [MilanKacurak/FormatGoogleCalendar#7]
Dear Milan

First of all, thank you for your awesome formatter.
Is it (already) possible to use it with a private calendar, will it be implemented soon or is it not possible at all, because of google?

**Comment by MilanLund** [comment]
@jonathanwinter123 I have checked that. In the Google API Manager you are able to generate a key with specific restrictions and use it as the "key" parameter in your calendar url "https://www.googleapis.com/calendar/v3/calendars/{calendarid}/events?key={Your Public API Key}". If an environment in which the "FormatGoogleCalendar" script is executed doesn't fit the restrictions Google doesn't return requested calendar JSON output. So there is nothing to do on the side of the script to make Google return a correct response.
