### ISSUE TITLE
[Feature Request]: Webpage Styling

### ISSUE THREAD

**Issue by covertmichael** [MilanKacurak/FormatGoogleCalendar#9]
I am new at this and I am not sure if someone has a solution. When I pull the information from the Google Calendar and display it on the webpage it is working. What I want to do it be able to style it and make it fit the rest of the page as far as font size, bold, color, etc... Is there a solution to this? Thanks for all of the help and support.

**Comment by MilanLund** [comment]
@covertmichael The solution is CSS. Just inspect DOM of the events list in dev tools in your browser to get know what selectors you need to use in your CSS file.
